#!/bin/bash
set -e

if [[ $EUID !=  0 ]]; then
	echo "You must run this as root!"
	exit 1
fi

if [[ ! -e /etc/conf.d/mediaserver ]]; then
	echo "Please create /etc/conf.d/mediaserver before running this!"
	echo "An example can be found in this folder"
	exit 1
fi

source /etc/conf.d/mediaserver

dir="$(dirname "$(readlink -f "$0")")"

mkdir -p /usr/lib/mediaserver
rsync -r "$dir/files/mediaserver/" /usr/lib/mediaserver/

for variable in JACKETT_DNS SONARR_DNS TRANSMISSION_DNS COUCHPOTATO_DNS; do 
	value=$(eval echo "\$$variable")
	for file in /usr/lib/mediaserver/nginx/sites-enabled/*; do
		sed -i "s|__${variable}__|$value|g" "$file"
	done
done

mkdir -p /etc/cron.d
cp "$dir/files/mediaserver.service" /etc/systemd/system/mediaserver.service
ln -sf "$dir/files/check-mediaserver.cron" "/etc/cron.d/check-mediaserver.cron"
ln -sf "$dir/files/restart-mediaserver.cron" "/etc/cron.d/restart-mediaserver.cron"

mkdir -p /etc/samba
cp "$dir/files/smb.conf" "/etc/samba/smb.conf"
sed -i "s|__CONFIG_DIR__|$CONFIG_DIR|g" /etc/samba/smb.conf

systemctl daemon-reload
systemctl enable mediaserver
systemctl status smbd &>/dev/null && systemctl restart smbd
